fix: DO NOT MERGE: stkOSMO migration
persistenceOne/persistenceCore pull request #253
Opened 2023-10-26 11:52 UTC by kruspy

2023-10-26 13:00 UTC, kruspy commented
The upgrade test keeps failing. I haven't seen this before and it looks like it is not related with the test itself.

@xlab

2023-10-26 13:28 UTC, xlab commented
> The upgrade test keeps failing. I haven't seen this before and it looks like it is not related with the test itself.
> 
> @xlab

Image `persistenceone/persistencecore:v10.0.0` has been created on `arm64` machine while it was expected to be done on `x86_64` machine, I will reupload.

2023-10-26 13:38 UTC, puneet2019 commented
I remember commenting this, but don't know where it went.

> LGTM, can we make sure while tagging we tag it with `testnet` in the title, it might be confusing for validators since this will never go on mainnet. 
And @kruspy are you sure you have tested this, because SDK docs ask to not [write while iterating](https://github.com/persistenceOne/cosmos-sdk/blob/v47-lsm/store/types/store.go#L232-L233)

2023-10-26 13:55 UTC, xlab commented
https://github.com/persistenceOne/persistenceCore/pull/253#issuecomment-1781147134

Makes sense, just wanted to keep it as closest to semver naming as possible.
`v10.1.0-rc1` or `v10.1.0-testnet` will do.

2023-10-26 19:03 UTC, xlab approved these changes
LGTM

2023-10-26 19:05 UTC, xlab requested changes
Ah, iterator still writes

2023-10-26 19:05 UTC, xlab commented on app/upgrades/v10.1.0-testnet/upgrades.go
> +				mStore.Delete(liquidstakeibctypes.GetDepositStoreKey(deposit.ChainId, deposit.Epoch))
A valid concern raised by @puneet2019  – this write must be outside the iterator. Collect records into an array and delete them after iteration is done.

2023-10-26 19:05 UTC, xlab commented on app/upgrades/v10.1.0-testnet/upgrades.go
> +				mStore.Delete(liquidstakeibctypes.GetLSMDepositStoreKey(deposit.ChainId, deposit.DelegatorAddress, deposit.Denom))
same here and other places

2023-12-18 20:49 UTC, puneet2019 commented
@kruspy can we close this PR?

2024-01-05 07:20 UTC, closed without merging