Updated Dockerfile to use the latest Go version 1.22 and added Docker…
persistenceOne/persistenceCore pull request #292
Opened 2024-02-21 08:41 UTC by anishsajikumar-devsecops

… build and push pipeline

## 1. Overview

## 2. Implementation details

## 3. How to test/use

## 4. Checklist

- [ ] Does the Readme need to be updated?

## 5. Limitations (optional)

## 6. Future Work (optional)

2024-02-21 11:27 UTC, xlab requested changes
The workflow there is different from one that I proposed to use as the reference
https://github.com/noble-assets/noble/blob/main/.github/workflows/docker-publish.yaml

If there are any obvious reasons that prevent us from using the same approach, we can discuss those.

2024-02-21 11:27 UTC, xlab commented on docker/persistencecore/Dockerfile
> +FROM golang:1.22.0-alpine3.18 AS go-builder
Please don't bump Go version, I wrote that we keep on `golang:1.21.x` until it's upgraded in heighliner there
https://github.com/strangelove-ventures/heighliner/blob/c88e63a992c9cb02c0089e7074acb19248f6fbc7/builder/go_versions.go#L15

2024-02-21 11:27 UTC, xlab commented on .github/workflows/docker_build_and_push.yml
> +      - 'main'
I think we shouldn't push images on docker hub that are not associated with a release.

2024-02-21 11:27 UTC, xlab commented on .github/workflows/docker_build_and_push.yml
> +          build-args: CONFIG_PATH=./chains.yaml
Wait, is it using heighliner?

2024-02-28 23:53 UTC, xlab requested changes

2024-02-28 23:53 UTC, xlab commented on README.md
> +![Persistence Core](https://www.asiacryptotoday.com/wp-content/uploads/2020/09/persistence-protocol.jpg)
Please update the README in a separate PR. Changing CI pipeline for Docker is a functional concern, the README text is non-functional concern, we should separate such things in different PRs.

2024-02-28 23:53 UTC, xlab commented on README.md
> +![Persistence Core](https://www.asiacryptotoday.com/wp-content/uploads/2020/09/persistence-protocol.jpg)
Oh, and don't reference JPEGs from 3rd party websites please in any file of the official codebase

2024-03-30 07:14 UTC, ajeet97 commented
Heighliner image CI added here - https://github.com/persistenceOne/persistenceCore/pull/313

2025-02-28 05:35 UTC, closed without merging