Upgraded cosmos version to v0.44
persistenceOne/persistenceCore pull request #64
Opened 2022-01-05 11:30 UTC by arhamchordia

2022-01-06 06:27 UTC, avkr003 requested changes

2022-01-06 06:32 UTC, avkr003 requested changes

2022-01-06 06:32 UTC, avkr003 commented on application/initialize/addGenesisAccountCommand.go
> +			depCdc := clientCtx.Codec
can avoid creating this varaiable now

2022-01-06 06:32 UTC, avkr003 commented on application/base.go
>  	upgradeKeeper := sdkUpgradeKeeper.NewKeeper(
`app.UpgradeKeeper.SetUpgradeHandler` missing

https://github.com/cosmos/gaia/blob/v6.0.0/app/app.go#L567

2022-01-20 09:28 UTC, puneet2019 approved these changes

2022-01-20 09:48 UTC, persistenceAdmin approved these changes

2022-01-20 09:56 UTC, closed without merging

2022-01-27 08:36 UTC, puneet2019 commented
@faddat I was think going back to back upgrades? first to 44, then 45.
we spent quite some time testing v44 upgrade. only thing we are waiting on is some resolution here- https://github.com/cosmos/cosmos-sdk/issues/10712