LiquidStaking module
persistenceOne/persistenceCore pull request #81
Opened 2022-06-14 06:51 UTC by bahdotsh

2022-06-15 08:20 UTC, puneet2019 requested changes

2022-06-15 08:20 UTC, puneet2019 commented on proto/persistence/halving/v1beta1/liquidstaking.proto
> +option go_package = "github.com/crescent-network/crescent/x/liquidstaking/types";
fix package to persistenceCore

2022-06-23 05:08 UTC, Anmol1696 commented
Move this to pstake-native

2022-06-23 06:07 UTC, Anmol1696 commented
Closing the PR since to be moved to pstake-native repo.

2022-06-23 06:07 UTC, closed without merging