Anmol/release static
persistenceOne/persistenceCore pull request #96
Opened 2022-08-02 12:59 UTC by Anmol1696

## 1. Overview

Create static release binaries in actions via building in docker.
Combine build and publish into one step.
Inspiration: https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/release.yml

## 2. Implementation details
* Create `Dockerfile.release` which is used for release
* Move dockerfiles in `docker` dir
* Add make commands for release yaml
* Rename `deploy.yml` to `release.yml`
* Build based on platform, instead of having 2 commands for 2 platforms, we give `PLATFORM` as variable

## 3. How to test/use
* Run `make release-build-platform PLATFORM=amd64 VERSION=test`
* Run `make release-build-platform PLATFORM=arm64 VERSION=test`
* Run `make release-git release-sha`
* Check the `release/` dir

## 4. Checklist
- [ ] Does the Readme need to be updated?

## 5. Limitations (optional)
* For buiilding multi-platform binaries, need to call the make command 2 times
* Additional `docker/Dockerfile.release` dockerfile, maybe we need to find a way to combine the 2

## 6. Future Work (optional)
* Combine docker files into more unified images

2022-08-04 07:00 UTC, Anmol1696 commented on .github/workflows/release.yml
> +        uses: actions/checkout@v2
mhh does not matter much, but sure can change it

2022-08-04 07:01 UTC, Anmol1696 commented on .github/workflows/release.yml
> +        uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v3
```

2022-08-04 08:17 UTC, puneet2019 approved these changes

2022-08-05 15:11 UTC, snj33v commented on Makefile
> +release-git:
github does this for us

2022-08-05 15:16 UTC, snj33v commented on Makefile
> -build-reproducible: go.sum
this really useful have a command to do reproducible builds

2022-08-05 15:19 UTC, snj33v commented on Makefile
> -build-reproducible: go.sum
we also need  to expand on this based on
https://github.com/cosmos/gaia/pull/523

2022-08-05 15:28 UTC, snj33v commented on .github/workflows/release.yml
> +# A workflow run is made up of one or more jobs that can run sequentially or in parallel
please use runs-on: ${{ matrix.config.os }}.
and create builds for arch using https://github.com/marketplace/actions/run-on-architecture

2022-08-05 15:36 UTC, snj33v requested changes
our discussion on building static binaries aside, we need to orchestrate GitHub actions effectively,

2022-08-09 05:27 UTC, Anmol1696 commented
@snj33v want to open this PR again, after our talk. 
As we discussed we will add a separate feature request that will give validators option to have shared library non static binaries as well.
For now we will keep releasing new binaries when the underlying c libraries update

2022-08-09 05:33 UTC, snj33v approved these changes

2022-08-09 05:42 UTC, merged